In [1]:
import torch
import torch.nn

In [2]:
from model import Generator, InfoDiscriminator

In [5]:
dataset = 'celeba'
img_size_bc = (11, 11) if dataset == 'mnist' else (41, 51)
channels = 1 if dataset == 'mnist' else 3
parametric_features = 3
noise_features = 5

In [6]:
gen = Generator(noise_features, parametric_features, img_size_bc, channels, dataset)
dis = InfoDiscriminator(parametric_features, img_size_bc, channels, dataset)

In [7]:
x = torch.rand(2, 8)
x

tensor([[0.9985, 0.5096, 0.8375, 0.6382, 0.7499, 0.5331, 0.2489, 0.2103],
        [0.2347, 0.8131, 0.5782, 0.8086, 0.0353, 0.1629, 0.3477, 0.5652]])

In [8]:
res = gen(x)
res.shape

torch.Size([2, 3, 178, 218])

In [9]:
dis(res)

(tensor([[-0.0742],
         [ 0.3024]], grad_fn=<AddmmBackward>),
 tensor([[ 0.2337, -0.1606, -0.4467],
         [-0.2973, -0.8055, -0.3850]], grad_fn=<AddmmBackward>))